---

apiVersion: v1
kind: Secret
metadata:
  name: datastream-artifactregistry-test
  namespace: datastream
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #CENSORED

---

apiVersion: v1
kind: Secret
metadata:
  name: datastream-helaseid-test
type: Opaque
data:
  TEAMS_WEBHOOK_URL: #CENSORED
  TZ: QXNpYS9KYWthcnRh

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datastream-helaseid-test
  namespace: datastream
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datastream-helaseid-test
  namespace: datastream
subjects:
  - kind: ServiceAccount
    name: datastream-helaseid-test
    namespace: datastream
roleRef:
  kind: Role
  name: datastream-helaseid-test
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: datastream-helaseid-test
  namespace: datastream

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: datastream-helaseid-test
  namespace: datastream
data:
  .env: |
    IPS=("10.10.2.6" "10.10.2.7" "10.190.2.8")
    PORT=9092
    MAX_RETRY=10
    DELAY=0.0001
    LOG_LEVEL=INFO
    NAMESPACE=datastream
    SERVICE_NAME=datastream-redpandaapi-test
    NOTIFICATION_ENABLED=true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastream-helaseid-test
  namespace: datastream
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: helaseid
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: helaseid
    spec:
      serviceAccountName: datastream-helaseid-test
      containers:
      - image: #TBA
        imagePullPolicy: IfNotPresent
        name: helaseid
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/config.env
          name: config-volume
          subPath: config.env
        resources:        
          requests:                                         
            cpu: 0.001
            memory: 50Mi
          limits:
            cpu: 0.1
            memory: 200Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: datastream-artifactregistry-test
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: datastream-helaseid-test
        name: config-volume

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: datastream-helaseid-test
  namespace: datastream
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datastream-helaseid-test
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50

---
